name: Flutter Build Android

on:
  push:
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.2' # Specify the Flutter version you want to use

    - name: Install dependencies
      run: flutter pub get

    - name: Build for Android
      run: flutter build apk --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-android
        path: build/app/outputs/flutter-apk/app-release.apk