name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.2' # Specify the Flutter version you want to use

    - name: Install dependencies
      run: flutter pub get

    - name: Install Ninja (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install ninja-build

    - name: Build for ${{ matrix.os }}
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          flutter build linux
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          flutter build macos
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          flutter build windows
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-${{ matrix.os }}
        path: |
          build/linux/x64/release/bundle/**
          build/macos/Build/Products/Release/**
          build/windows/runner/Release/**