name: Flutter Build iOS

on:
  push:
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.2' # Specify the Flutter version you want to use

    - name: Install dependencies
      run: flutter pub get

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_12.4.app

    - name: Build for iOS
      run: flutter build ios --release --no-codesign

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: build-ios
        path: build/ios/iphoneos/